/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.savancys.model.impl;

import com.savancys.model.ContactUs;
import com.savancys.service.ContactUsLocalServiceUtil;

/**
 * The extended model base implementation for the ContactUs service. Represents a row in the &quot;ContactUs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactUsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactUsImpl
 * @see ContactUs
 * @generated
 */
public abstract class ContactUsBaseImpl
	extends ContactUsModelImpl implements ContactUs {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact us model instance should use the <code>ContactUs</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ContactUsLocalServiceUtil.addContactUs(this);
		}
		else {
			ContactUsLocalServiceUtil.updateContactUs(this);
		}
	}

}