/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.savancys.model.impl;

import com.savancys.model.JobApplicant;
import com.savancys.service.JobApplicantLocalServiceUtil;

/**
 * The extended model base implementation for the JobApplicant service. Represents a row in the &quot;JobApplicant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JobApplicantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JobApplicantImpl
 * @see JobApplicant
 * @generated
 */
public abstract class JobApplicantBaseImpl
	extends JobApplicantModelImpl implements JobApplicant {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a job applicant model instance should use the <code>JobApplicant</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			JobApplicantLocalServiceUtil.addJobApplicant(this);
		}
		else {
			JobApplicantLocalServiceUtil.updateJobApplicant(this);
		}
	}

}