/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.savancys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContactUs service. Represents a row in the &quot;ContactUs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.savancys.model.impl.ContactUsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.savancys.model.impl.ContactUsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactUs
 * @generated
 */
@ProviderType
public interface ContactUsModel
	extends BaseModel<ContactUs>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact us model instance should use the {@link ContactUs} interface instead.
	 */

	/**
	 * Returns the primary key of this contact us.
	 *
	 * @return the primary key of this contact us
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact us.
	 *
	 * @param primaryKey the primary key of this contact us
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this contact us.
	 *
	 * @return the uuid of this contact us
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this contact us.
	 *
	 * @param uuid the uuid of this contact us
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the contact ID of this contact us.
	 *
	 * @return the contact ID of this contact us
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this contact us.
	 *
	 * @param contactId the contact ID of this contact us
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the group ID of this contact us.
	 *
	 * @return the group ID of this contact us
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact us.
	 *
	 * @param groupId the group ID of this contact us
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact us.
	 *
	 * @return the company ID of this contact us
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact us.
	 *
	 * @param companyId the company ID of this contact us
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact us.
	 *
	 * @return the user ID of this contact us
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact us.
	 *
	 * @param userId the user ID of this contact us
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact us.
	 *
	 * @return the user uuid of this contact us
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contact us.
	 *
	 * @param userUuid the user uuid of this contact us
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact us.
	 *
	 * @return the user name of this contact us
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact us.
	 *
	 * @param userName the user name of this contact us
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact us.
	 *
	 * @return the create date of this contact us
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact us.
	 *
	 * @param createDate the create date of this contact us
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact us.
	 *
	 * @return the modified date of this contact us
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact us.
	 *
	 * @param modifiedDate the modified date of this contact us
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the inquiry type of this contact us.
	 *
	 * @return the inquiry type of this contact us
	 */
	@AutoEscape
	public String getInquiryType();

	/**
	 * Sets the inquiry type of this contact us.
	 *
	 * @param inquiryType the inquiry type of this contact us
	 */
	public void setInquiryType(String inquiryType);

	/**
	 * Returns the first name of this contact us.
	 *
	 * @return the first name of this contact us
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this contact us.
	 *
	 * @param firstName the first name of this contact us
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this contact us.
	 *
	 * @return the last name of this contact us
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this contact us.
	 *
	 * @param lastName the last name of this contact us
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the phone number of this contact us.
	 *
	 * @return the phone number of this contact us
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this contact us.
	 *
	 * @param phoneNumber the phone number of this contact us
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the email of this contact us.
	 *
	 * @return the email of this contact us
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this contact us.
	 *
	 * @param email the email of this contact us
	 */
	public void setEmail(String email);

	/**
	 * Returns the company name of this contact us.
	 *
	 * @return the company name of this contact us
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this contact us.
	 *
	 * @param companyName the company name of this contact us
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the country of this contact us.
	 *
	 * @return the country of this contact us
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this contact us.
	 *
	 * @param country the country of this contact us
	 */
	public void setCountry(String country);

	/**
	 * Returns the additional info of this contact us.
	 *
	 * @return the additional info of this contact us
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this contact us.
	 *
	 * @param additionalInfo the additional info of this contact us
	 */
	public void setAdditionalInfo(String additionalInfo);

	/**
	 * Returns the fullname of this contact us.
	 *
	 * @return the fullname of this contact us
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this contact us.
	 *
	 * @param fullname the fullname of this contact us
	 */
	public void setFullname(String fullname);

	@Override
	public ContactUs cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}