/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.savancys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the JobApplicant service. Represents a row in the &quot;JobApplicant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.savancys.model.impl.JobApplicantModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.savancys.model.impl.JobApplicantImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JobApplicant
 * @generated
 */
@ProviderType
public interface JobApplicantModel
	extends BaseModel<JobApplicant>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job applicant model instance should use the {@link JobApplicant} interface instead.
	 */

	/**
	 * Returns the primary key of this job applicant.
	 *
	 * @return the primary key of this job applicant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job applicant.
	 *
	 * @param primaryKey the primary key of this job applicant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job applicant ID of this job applicant.
	 *
	 * @return the job applicant ID of this job applicant
	 */
	public long getJobApplicantID();

	/**
	 * Sets the job applicant ID of this job applicant.
	 *
	 * @param jobApplicantID the job applicant ID of this job applicant
	 */
	public void setJobApplicantID(long jobApplicantID);

	/**
	 * Returns the group ID of this job applicant.
	 *
	 * @return the group ID of this job applicant
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this job applicant.
	 *
	 * @param groupId the group ID of this job applicant
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this job applicant.
	 *
	 * @return the company ID of this job applicant
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this job applicant.
	 *
	 * @param companyId the company ID of this job applicant
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this job applicant.
	 *
	 * @return the user ID of this job applicant
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this job applicant.
	 *
	 * @param userId the user ID of this job applicant
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job applicant.
	 *
	 * @return the user uuid of this job applicant
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this job applicant.
	 *
	 * @param userUuid the user uuid of this job applicant
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this job applicant.
	 *
	 * @return the user name of this job applicant
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this job applicant.
	 *
	 * @param userName the user name of this job applicant
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this job applicant.
	 *
	 * @return the create date of this job applicant
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this job applicant.
	 *
	 * @param createDate the create date of this job applicant
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job applicant.
	 *
	 * @return the modified date of this job applicant
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job applicant.
	 *
	 * @param modifiedDate the modified date of this job applicant
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this job applicant.
	 *
	 * @return the first name of this job applicant
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this job applicant.
	 *
	 * @param firstName the first name of this job applicant
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this job applicant.
	 *
	 * @return the last name of this job applicant
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this job applicant.
	 *
	 * @param lastName the last name of this job applicant
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the phone number of this job applicant.
	 *
	 * @return the phone number of this job applicant
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this job applicant.
	 *
	 * @param phoneNumber the phone number of this job applicant
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the email of this job applicant.
	 *
	 * @return the email of this job applicant
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this job applicant.
	 *
	 * @param email the email of this job applicant
	 */
	public void setEmail(String email);

	/**
	 * Returns the job type of this job applicant.
	 *
	 * @return the job type of this job applicant
	 */
	@AutoEscape
	public String getJobType();

	/**
	 * Sets the job type of this job applicant.
	 *
	 * @param jobType the job type of this job applicant
	 */
	public void setJobType(String jobType);

	/**
	 * Returns the state of this job applicant.
	 *
	 * @return the state of this job applicant
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this job applicant.
	 *
	 * @param state the state of this job applicant
	 */
	public void setState(String state);

	/**
	 * Returns the message of this job applicant.
	 *
	 * @return the message of this job applicant
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this job applicant.
	 *
	 * @param message the message of this job applicant
	 */
	public void setMessage(String message);

	/**
	 * Returns the file ID of this job applicant.
	 *
	 * @return the file ID of this job applicant
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this job applicant.
	 *
	 * @param fileId the file ID of this job applicant
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the job post ID of this job applicant.
	 *
	 * @return the job post ID of this job applicant
	 */
	public long getJobPostId();

	/**
	 * Sets the job post ID of this job applicant.
	 *
	 * @param jobPostId the job post ID of this job applicant
	 */
	public void setJobPostId(long jobPostId);

	/**
	 * Returns the skill of this job applicant.
	 *
	 * @return the skill of this job applicant
	 */
	@AutoEscape
	public String getSkill();

	/**
	 * Sets the skill of this job applicant.
	 *
	 * @param skill the skill of this job applicant
	 */
	public void setSkill(String skill);

	/**
	 * Returns the web authorization of this job applicant.
	 *
	 * @return the web authorization of this job applicant
	 */
	@AutoEscape
	public String getWebAuthorization();

	/**
	 * Sets the web authorization of this job applicant.
	 *
	 * @param webAuthorization the web authorization of this job applicant
	 */
	public void setWebAuthorization(String webAuthorization);

	@Override
	public JobApplicant cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}