/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.savancys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the JobPost service. Represents a row in the &quot;JobPost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.savancys.model.impl.JobPostModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.savancys.model.impl.JobPostImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JobPost
 * @generated
 */
@ProviderType
public interface JobPostModel
	extends BaseModel<JobPost>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job post model instance should use the {@link JobPost} interface instead.
	 */

	/**
	 * Returns the primary key of this job post.
	 *
	 * @return the primary key of this job post
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job post.
	 *
	 * @param primaryKey the primary key of this job post
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this job post.
	 *
	 * @return the uuid of this job post
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this job post.
	 *
	 * @param uuid the uuid of this job post
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the job post ID of this job post.
	 *
	 * @return the job post ID of this job post
	 */
	public long getJobPostId();

	/**
	 * Sets the job post ID of this job post.
	 *
	 * @param jobPostId the job post ID of this job post
	 */
	public void setJobPostId(long jobPostId);

	/**
	 * Returns the group ID of this job post.
	 *
	 * @return the group ID of this job post
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this job post.
	 *
	 * @param groupId the group ID of this job post
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this job post.
	 *
	 * @return the company ID of this job post
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this job post.
	 *
	 * @param companyId the company ID of this job post
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this job post.
	 *
	 * @return the user ID of this job post
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this job post.
	 *
	 * @param userId the user ID of this job post
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job post.
	 *
	 * @return the user uuid of this job post
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this job post.
	 *
	 * @param userUuid the user uuid of this job post
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this job post.
	 *
	 * @return the user name of this job post
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this job post.
	 *
	 * @param userName the user name of this job post
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this job post.
	 *
	 * @return the create date of this job post
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this job post.
	 *
	 * @param createDate the create date of this job post
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job post.
	 *
	 * @return the modified date of this job post
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job post.
	 *
	 * @param modifiedDate the modified date of this job post
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this job post.
	 *
	 * @return the active of this job post
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this job post is active.
	 *
	 * @return <code>true</code> if this job post is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this job post is active.
	 *
	 * @param active the active of this job post
	 */
	public void setActive(boolean active);

	/**
	 * Returns the delete of this job post.
	 *
	 * @return the delete of this job post
	 */
	public boolean getDelete();

	/**
	 * Returns <code>true</code> if this job post is delete.
	 *
	 * @return <code>true</code> if this job post is delete; <code>false</code> otherwise
	 */
	public boolean isDelete();

	/**
	 * Sets whether this job post is delete.
	 *
	 * @param delete the delete of this job post
	 */
	public void setDelete(boolean delete);

	/**
	 * Returns the job post name of this job post.
	 *
	 * @return the job post name of this job post
	 */
	@AutoEscape
	public String getJobPostName();

	/**
	 * Sets the job post name of this job post.
	 *
	 * @param jobPostName the job post name of this job post
	 */
	public void setJobPostName(String jobPostName);

	/**
	 * Returns the experience of this job post.
	 *
	 * @return the experience of this job post
	 */
	@AutoEscape
	public String getExperience();

	/**
	 * Sets the experience of this job post.
	 *
	 * @param experience the experience of this job post
	 */
	public void setExperience(String experience);

	/**
	 * Returns the qualification of this job post.
	 *
	 * @return the qualification of this job post
	 */
	@AutoEscape
	public String getQualification();

	/**
	 * Sets the qualification of this job post.
	 *
	 * @param qualification the qualification of this job post
	 */
	public void setQualification(String qualification);

	/**
	 * Returns the location of this job post.
	 *
	 * @return the location of this job post
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this job post.
	 *
	 * @param location the location of this job post
	 */
	public void setLocation(String location);

	/**
	 * Returns the skills of this job post.
	 *
	 * @return the skills of this job post
	 */
	@AutoEscape
	public String getSkills();

	/**
	 * Sets the skills of this job post.
	 *
	 * @param skills the skills of this job post
	 */
	public void setSkills(String skills);

	/**
	 * Returns the description of this job post.
	 *
	 * @return the description of this job post
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this job post.
	 *
	 * @param description the description of this job post
	 */
	public void setDescription(String description);

	/**
	 * Returns the salary of this job post.
	 *
	 * @return the salary of this job post
	 */
	@AutoEscape
	public String getSalary();

	/**
	 * Sets the salary of this job post.
	 *
	 * @param salary the salary of this job post
	 */
	public void setSalary(String salary);

	/**
	 * Returns the status of this job post.
	 *
	 * @return the status of this job post
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this job post is status.
	 *
	 * @return <code>true</code> if this job post is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this job post is status.
	 *
	 * @param status the status of this job post
	 */
	public void setStatus(boolean status);

	@Override
	public JobPost cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}