/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.savancys.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LcaPosting service. Represents a row in the &quot;LCA_Posting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.savancys.model.impl.LcaPostingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.savancys.model.impl.LcaPostingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LcaPosting
 * @generated
 */
@ProviderType
public interface LcaPostingModel
	extends BaseModel<LcaPosting>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lca posting model instance should use the {@link LcaPosting} interface instead.
	 */

	/**
	 * Returns the primary key of this lca posting.
	 *
	 * @return the primary key of this lca posting
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lca posting.
	 *
	 * @param primaryKey the primary key of this lca posting
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this lca posting.
	 *
	 * @return the uuid of this lca posting
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this lca posting.
	 *
	 * @param uuid the uuid of this lca posting
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lca posting ID of this lca posting.
	 *
	 * @return the lca posting ID of this lca posting
	 */
	public long getLcaPostingId();

	/**
	 * Sets the lca posting ID of this lca posting.
	 *
	 * @param lcaPostingId the lca posting ID of this lca posting
	 */
	public void setLcaPostingId(long lcaPostingId);

	/**
	 * Returns the group ID of this lca posting.
	 *
	 * @return the group ID of this lca posting
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lca posting.
	 *
	 * @param groupId the group ID of this lca posting
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this lca posting.
	 *
	 * @return the company ID of this lca posting
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lca posting.
	 *
	 * @param companyId the company ID of this lca posting
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lca posting.
	 *
	 * @return the user ID of this lca posting
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lca posting.
	 *
	 * @param userId the user ID of this lca posting
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lca posting.
	 *
	 * @return the user uuid of this lca posting
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lca posting.
	 *
	 * @param userUuid the user uuid of this lca posting
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lca posting.
	 *
	 * @return the user name of this lca posting
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lca posting.
	 *
	 * @param userName the user name of this lca posting
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lca posting.
	 *
	 * @return the create date of this lca posting
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lca posting.
	 *
	 * @param createDate the create date of this lca posting
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lca posting.
	 *
	 * @return the modified date of this lca posting
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lca posting.
	 *
	 * @param modifiedDate the modified date of this lca posting
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the designation of this lca posting.
	 *
	 * @return the designation of this lca posting
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this lca posting.
	 *
	 * @param designation the designation of this lca posting
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the location of this lca posting.
	 *
	 * @return the location of this lca posting
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this lca posting.
	 *
	 * @param location the location of this lca posting
	 */
	public void setLocation(String location);

	/**
	 * Returns the o net code of this lca posting.
	 *
	 * @return the o net code of this lca posting
	 */
	@AutoEscape
	public String getONetCode();

	/**
	 * Sets the o net code of this lca posting.
	 *
	 * @param oNetCode the o net code of this lca posting
	 */
	public void setONetCode(String oNetCode);

	/**
	 * Returns the description of this lca posting.
	 *
	 * @return the description of this lca posting
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this lca posting.
	 *
	 * @param description the description of this lca posting
	 */
	public void setDescription(String description);

	@Override
	public LcaPosting cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}